---
logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

rsa:
  private-key: classpath:keys/private.pem
  public-key: classpath:keys/public.pem